### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by thunderer** [thunderer/Platenum#1]
- [x] PHP 8.0 attribute enums (#28),
- [x] (dropped) ~~events? (`(before|after)Resolve`, etc.)~~,
- [x] .gitattributes,
- [x] method to create instances of all members ("warm up" the whole type) - `getMembersAndValues()`,
- [ ] README: expand JSON serialization section, mention that it requires just adding the interface,
- [ ] ordinal enums.

## v0.3

- [x] custom exceptions (#8),
- [x] Doctrine ORM type mapping (#12),
- [x] mutation testing with Infection (#14),
- [x] static analysis markers (Psalm, PHPStan) (#9),
- [x] enum callback source (#13),
- [x] enum external source (DB, file, Redis, dependencies) - solved in callback PR (#13),
- [x] verify that all member values are of the same type (covered in #13).
